micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/`}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

